apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # Base64 encoded MongoDB root username
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= # Base64 encoded MongoDB root password