apiVersion: v1
kind: Service
metadata:
  name: weather-app-demo-service
  labels:
    app: weather-app-demo
spec:
  type: ClusterIP # Exposes the service within the cluster
  selector:
    app: weather-app-demo
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service       
      targetPort: 5000 # Port on the container to forward traffic to

