apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-demo-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: weather-app-demo-container
          image: registry/weather-app-demo:v1.0.0
          env:
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo-db-service:27017/weather-db" 
          resources:
            requests:
              memory: "256Mi" 
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
