apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app-demo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  
spec:
  rules:
    - host: weather-app-demo.com   
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-app-demo-service
                port:
                  number: 80