apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cHJvZA== # Base64 encoded MongoDB root username
  MONGO_INITDB_ROOT_PASSWORD: cHJvZA== # Base64 encoded MongoDB root password