apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-demo-deployment
spec:
  replicas: 2 # Number of pod replicas to run
  template:
    spec:
      containers:
        - name: weather-app-demo-container
          image: registry/weather-app-demo:v1.0.0dev # Container image and version
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret # Reference to the Secret for the API key
                  key: api_key
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials # Reference to the Secret for MongoDB credentials
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials # Reference to the Secret for MongoDB credentials
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources: # Resource requests and limits
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"