apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_USER: ZGV2b3VzZXI=  # 'devuser' base64 codiert
  MONGO_PASSWORD: ZGV2cGFzc3dvcmQ=  # 'devpassword' base64 codiert