apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: ZGV2dXNlcg== # Base64 encoded MongoDB root username
  MONGO_INITDB_ROOT_PASSWORD: ZGV2cGFzcw== # Base64 encoded MongoDB root password