apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: credential-rotator
subjects:
  - kind: ServiceAccount
    name: credential-rotator
roleRef:
  kind: Role
  name: credential-rotator
  apiGroup: rbac.authorization.k8s.io
