apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: credential-rotator
rules:
  - apiGroups: [""]
    resources: ["secrets"] # Access to secrets
    verbs: ["get", "patch"] # Allowed actions: get and patch secrets
  - apiGroups: ["apps"]
    resources: ["deployments"] # Access to deployments
    verbs: ["get", "patch"] # Allowed actions: get and patch deployments
