apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: credential-rotator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
