apiVersion: batch/v1
kind: CronJob
metadata:
  name: rotate-mongo-credentials
spec:
  schedule: "*/1 * * * *"  # Alle 1 Minute
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rotate-mongo-credentials-sa
          containers:
            - name: rotate-mongo-credentials
              image: busybox:1.35
              command:
                - /bin/sh
                - -c
                - |
                  NEW_PASSWORD=$(openssl rand -base64 32)  # Zufälliges Passwort
                  NEW_USER="mongo-user"
                  ENCODED_PASSWORD=$(echo -n $NEW_PASSWORD | base64)
                  ENCODED_USER=$(echo -n $NEW_USER | base64)

                  kubectl patch secret mongo-credentials --type='merge' \
                    -p="{\"data\":{\"MONGO_USER\":\"$ENCODED_USER\",\"MONGO_PASSWORD\":\"$ENCODED_PASSWORD\"}}"

                  echo "Successful"
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"
          restartPolicy: OnFailure