apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  
  name: rotate-mongo-credentials-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]  
    verbs: ["get", "patch"]  