version: '3.8'

services:
  web:
    image: weather-app:v1.0.1
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: